services:
  # app
  app:
    build: .  
    container_name: graph_rag_app
    env_file:
      - .env  
    depends_on:
      - neo4j 
    volumes:
      - ./src:/app/src 
  # Neo4j database
  neo4j:
    image: neo4j:latest
    container_name: neo4j_db
    ports:
      - "7474:7474" 
      - "7687:7687" 
    volumes:
      - ./neo4j_data:/data 
    environment:
      - NEO4J_AUTH=neo4j/${NEO4J_PASSWORD}